### ISSUE TITLE
How to link facebook account

### ISSUE THREAD

**Issue by yayolius** [strongloop/loopback-component-passport#125]
I tried to change, the example configuration for facebook login using the google link example, in order to create a link to the regular accounts, but nothing i try works at the end.
Can you help me with this?, or include and example in the documentation?

**Comment by jannyHou** [comment]
@yayolius I am trying to reproduce your question, but confused with 
> change, the example configuration for facebook login using the google link example

hmm...how could you change a **facebook** login according to a **google** link?
I also appreciate it if you could paste the config you are trying to change in comment:)

**Comment by yayolius** [comment]
Well, i think that the problem is that i really don't understand the differnece between auth and linking, i assume is that linking, means have an account already created and you want to "link" the current account with the social login.

I tried to do something like this
``
"facebook-login": {
   "provider": "facebook",
   "module": "passport-facebook",
   "clientID": "{facebook-client-id-1}",
   "clientSecret": "{facebook-client-secret-1}",
   "callbackURL": "http://localhost:3000/link/facebook/callback",
   "authPath": "/auth/facebook",
   "callbackPath": "/link/facebook/callback",
   "successRedirect": "/auth/account",
   "scope": ["email"],
  "link": true
 },
``

Thanks
Claudio

**Comment by jannyHou** [comment]
> i assume is that linking, means have an account already created and you want to "link" the current account with the social login

@yayolius sorry for responding late, yes your understand is correct.
And to get your link work, take facebook as an example, you need to replace the `cliendID` and `clientSecret` with your own fb credentials. Please follow this doc for details: https://docs.strongloop.com/display/public/LB/Third-party+login+using+Passport

**Comment by ebarault** [comment]
@jannyHou : hi,
i'm using the exact same configuration and when trying to GET on the link callback, i get the following error: 
```
XMLHttpRequest cannot load http://localhost:3000/link/facebook-token/callback?access_token=XXXXXX. The request was redirected to 'http://localhost:3000/link.html', which is disallowed for cross-origin requests that require preflight.
```
what it this `link.html` link supposed to be?

**Comment by ebarault** [comment]
@jannyHou Hi,
I'm running the exact same provider configuration and when doing a GET on the `/link/facebook` url, the request is redirected to `/link.html` all the time, which is not available. 
No further action is undertaken by loopback or passport from this stage, no entry is added in the UserCredential collection.
What is this `link.html` supposed to be?

**Comment by ehrasmo** [comment]
I'm getting the same link.html redirect after success using google authentication, no idea what's this link.html all about.

**Comment by danielmihai** [comment]
I don't get the link error, but when FB calls the callback with the code, it fails to link the account and redirects to the failureRedirect path from the Facebook provider configuration. the FB request succeeds, only the validation FB link operation fails on callback data validation. I have the passReqToCallback set to true.

**Comment by Jaco97** [comment]
same problem here, it redirects me to the failure page

**Comment by jannyHou** [comment]
@Jaco97 are you having this error with `loopback-example-passport` or your custom app?

**Comment by danielmihai** [comment]
The problem is with the component itself, i modified the code in the node
module to make the app work as expected.

**Comment by Jaco97** [comment]
@jannyHou  my app

**Comment by Jcbobo88** [comment]
@danielmihai  can you explain us when and how in order to obtain the same result( or if you can make a PR)?

**Comment by danielmihai** [comment]
I will reply as soon as I get the time today or tomorrow. Pretty caught up. If You need it immediately, you could checkout my loopback prototype and use the passport component from the node modules folder. I will submit a pull request with the corrected flow since there are a lot of people who have asked for it.


Thanks,
Daniel M. Colceag

**Comment by danielmihai** [comment]
Hi @Jcbobo88 ,

I forked the official repository now and I've seen it diverged a lot (as it normally would do so). I tried preparing for a pull request moments ago. I merged my changes in the current loopback-2.x branch. I have to fix some parts again, because the unit tests fail. I'll investigate further when I have/make the time.

Did you manage to make your passport flow work with the modified loopback-component-passport from my repo ? 

Best, 
Daniel.

**Comment by Jcbobo88** [comment]
Hi @danielmihai  ,
right now i'm using loopback 3.x  but i still have the issues, right now i'm moved on an other point of the facebook integration passport-facebook-token  but with an other issue,

i will try (as soon i can) to make passport-facebook link works 
Thanks you
