### ISSUE TITLE
Version 1.5.0 stopped working

### ISSUE THREAD

**Issue by sajmons** [strongloop/loopback-component-passport#73]
Raymond Feng: In change log for 1.5.0 version you stated: "Make sure passport is registered with session phase" but unfortunately I don't know how to do that. Is there any example available?

Best regards,
Simon Šander

**Comment by BerkeleyTrue** [comment]
@sajmons There was a breaking change from 1.4.0 to 1.5.0. This module now makes use of Loopback Middleware Phases http://docs.strongloop.com/display/public/LB/Defining+middleware I just finished the process [here](https://github.com/FreeCodeCamp/freecodecamp/tree/staging/server) if you want to see an example.

You will need to adapt your app to use this format in order to continue moving forward with this module.

@raymondfeng A patch is needed to revert the phase introduction and release a 1.6 fix and release a 2.0 that uses phases (since it is a breaking change).

**Comment by raymondfeng** [comment]
An example at https://github.com/strongloop/loopback-example-passport

**Comment by raymondfeng** [comment]
@BerkeleyTrue Good catch. I'll look into it.

**Comment by sajmons** [comment]
What about Microsoft Active Directory ms-ad example? I see that it's left out from every example.

**Comment by sajmons** [comment]
I have taken new code from server.js 1.5.0 and it worked! Thnx!

**Comment by superkhau** [comment]
@sajmons I assume your issue is resolved. Is this good to close?

**Comment by BerkeleyTrue** [comment]
The issue that 1.5.0 introduced breaking changes still exist. It forces users to either introduce loopback middleware phases or stick to 1.4.0

**Comment by superkhau** [comment]
@BerkeleyTrue TY, escalating to `bug` status.

@raymondfeng Reassigning to you for further instructions.

**Comment by sajmons** [comment]
I have switched to middleware solution but as Berkeley mentioned it is
a *breaking
change*.

2015-08-13 0:39 GMT+02:00 Simon Ho <notifications@github.com>:

> @BerkeleyTrue <https://github.com/BerkeleyTrue> TY, escalating to bug
> status.
>
> @raymondfeng <https://github.com/raymondfeng> Reassigning to you for
> further instructions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/loopback-component-passport/issues/73#issuecomment-130468466>
> .
>



-- 
lp,
Simon
